title = "Shows in AZ"
description = "Your guide to live music in Arizona"
base_url = "https://showsinaz.com"

compile_sass = true
minify_html = false
generate_feeds = true

[markdown]
highlight_code = false

[extra]
tagline = "Your guide to live music in Arizona"