name: Check Links

on:
  schedule:
    # Run every Monday at 9 AM EST (2 PM UTC)
    - cron: '0 14 * * 1'
  workflow_dispatch: # Allow manual trigger
  
jobs:
  check-links:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Check venue URLs
      run: |
        echo "::group::Checking venue URLs"
        python3 scripts/check_links.py --venue-urls-only --max-workers 5
        echo "::endgroup::"
      continue-on-error: true
    
    - name: Check content links
      run: |
        echo "::group::Checking content links"
        python3 scripts/check_links.py --content-links-only --max-workers 5
        echo "::endgroup::"
      continue-on-error: true
    
    - name: Create issue on failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          const { data: issues } = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['broken-links'],
            state: 'open'
          });
          
          if (issues.length === 0) {
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Broken links detected in venue URLs',
              body: `The automated link checker found broken links in the venue URLs.
              
              **Action Required:**
              1. Run \`make check-links\` locally to see the full report
              2. Update or remove broken venue URLs
              3. Consider updating venue mappings in \`scripts/normalize_venues.py\`
              
              **Commands to investigate:**
              - \`make check-venue-links\` - Check only venue URLs
              - \`make check-content-links\` - Check only content links
              - \`make check-links\` - Check all links
              
              This issue was automatically created by the link checking workflow.`,
              labels: ['broken-links', 'maintenance']
            });
          }