name: Clean up past events

on:
  schedule:
    - cron: '0 11 * * *'  # 6 AM EST (11 AM UTC)
  workflow_dispatch:  # Allow manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Remove past events
      run: ./remove_past_shows.sh
      
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if ! git diff --staged --quiet; then
          git commit -m "chore: remove past events (automated cleanup)"
          git push
        else
          echo "No past events to remove"
        fi